# Generated by Django 5.1 on 2025-03-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='nomi',
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Mavjud', 'Mavjud'), ('Band', 'Band')], default='available', max_length=10),
        ),
    ]
