# Generated by Django 5.1 on 2025-03-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_nomi_book_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='nomi',
        ),
    ]
