# Generated by Django 5.1 on 2025-03-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_title_book_nomi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='borrow_date',
            new_name='beriladigan_sanasi',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='status',
            new_name='holati',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='muallifi',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='return_date',
            new_name='olingan_sanasi',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='borrower',
            new_name='oluvchi',
        ),
        migrations.DeleteModel(
            name='BorrowRecord',
        ),
    ]
